### ISSUE TITLE
Run everything inside docker-compose

### ISSUE THREAD

**Issue by jasonrhaas** [codefordc/housing-insights#183]
Python environments are notoriously difficult to get set up, especially when dealing with data science packages.  Anaconda helps with this quite a bit, but I've found there can still be problems depending on the user's specific local environment.  Docker of course solves all of this, which is why I've started running everything that I can inside a docker-compose environment.

We could create a Python sandbox Docker image that is used to connect to the database, and has all the connections set up already so the user doesn't have to deal with figuring this out.  Docker-compose by default shares all the container ports with each other, so we don't have as many local port conflicts either.

We load the data from inside the Python Docker container, which runs the Conda environment.  This way there is no need for a user to install Conda or any packages on their local machine.

Something like this would work and just exist to run commands on:

```
    sandbox:
      build:
        context: .
        dockerfile: Dockerfile-sandbox
      volumes:
        - .:/code
      command: tail -f /dev/null
```

All of the code is mounted, so no need to worry about re-building the container on code changes, unless there is a new package requirement.
